### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Diduenjoy/gtm-website-popup-survey#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUri should be used on user provided values in the "url". These methods take in a single text argument and returns an encoded Uniform Resource Identifier (URI) by escaping special characters. It returns a string that represents the provided string encoded as a URI. You should use this method on "_diduenjoy.domain" when generating the url
('https' == protocol ? 'https' : 'http') + '://cdn.diduenjoy.' + _diduenjoy.domain + '/libs/due-popup.min.js'

**Comment by redpist** [comment]
I just published a new version adding the encodeUri.
Should I notify you on any other touchpoint?
